version: "3.9"

services:
  db:
    image: postgres:15
    container_name: 1337b04rd-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: 1337b04rd-minio
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000" # API
      - "9001:9001" # Web UI
    volumes:
      - minio_data:/data

  app:
    build: .
    container_name: 1337b04rd-app
    depends_on:
      - db
      - minio
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_USE_SSL: "false"
      S3_POST_BUCKET: ${S3_POST_BUCKET}
      S3_COMMENT_BUCKET: ${S3_COMMENT_BUCKET}

volumes:
  db_data:
  minio_data:
